project:
  type: website

website:
  title: "Shyam Dwaraknath"
  site-url: https://shyamd.github.io
  navbar:
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/shyam-dwaraknath/
format:
  html:
    theme: cosmo
    css: styles.css
